---

- name: count mysql timezones
  command: mysql -NBe "SELECT COUNT(*) FROM mysql.time_zone"
  register: mysql_timezones_count
  changed_when: false
  check_mode: no

- name: ensure timezone data is imported
  shell: "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql mysql"
  when: mysql_timezones_count.stdout|int < 1
  notify:
    - restart mysql

- name: setup timezone config file
  template:
    src: etc/my.cnf.d/timezone.cnf.j2
    dest: /etc/my.cnf.d/timezone.cnf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart mysql